# Generated by Django 5.0.3 on 2024-04-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.DateField(default='2024-04-04'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
