# Generated by Django 5.0.3 on 2024-04-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meal',
            name='image_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='desc',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
