# Generated by Django 5.0.3 on 2024-05-05 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('lemon', '0002_meal_image_meal_image_text_alter_meal_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lemon.meal')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authtoken.token')),
            ],
        ),
    ]
